services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - postgres

    environment:
      DATABASE_NAME: $DB_NAME
      DATABASE_USERNAME: $DB_USERNAME
      DATABASE_PASSWORD: $DB_PASSWORD
      DATABASE_HOST: $DB_HOST
      GITHUB_CLIENT_ID: $GITHUB_CLIENT_ID
      GITHUB_CLIENT_SECRETS: $GITHUB_CLIENT_SECRETS

    volumes:
      - .:/opt/app

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - "5432:5432"
    volumes:
      - ~/postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
